#!/usr/bin/env bash
# Interactive MCP production start: ask for WordPress URL + token per site (no JSON).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="${ENV_FILE:-.env.prod}"
COMPOSE="${DOCKER_COMPOSE:-docker compose}"

if [[ ! -t 0 ]] && [[ ! -r /dev/tty ]]; then
  echo "mcp-up needs an interactive terminal (or pass answers via /dev/tty)." >&2
  exit 1
fi

ask() {
  local prompt="$1"
  local default="${2:-}"
  local reply=""
  if [[ -n "$default" ]]; then
    printf "%s [%s]: " "$prompt" "$default" >/dev/tty
  else
    printf "%s: " "$prompt" >/dev/tty
  fi
  IFS= read -r reply </dev/tty || true
  if [[ -z "$reply" ]]; then
    reply="$default"
  fi
  printf '%s' "$reply"
}

ask_secret() {
  local prompt="$1"
  local reply=""
  printf "%s: " "$prompt" >/dev/tty
  # shellcheck disable=SC2162
  IFS= read -rs reply </dev/tty || true
  printf '\n' >/dev/tty
  printf '%s' "$reply"
}

ask_yes_no() {
  local prompt="$1"
  local default="${2:-n}"
  local hint="y/N"
  [[ "$default" == "y" || "$default" == "Y" ]] && hint="Y/n"
  local reply
  reply="$(ask "$prompt ($hint)" "")"
  if [[ -z "$reply" ]]; then
    reply="$default"
  fi
  case "$reply" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd python3
require_cmd docker

if [[ -f "$ENV_FILE" ]]; then
  echo "Found existing $ENV_FILE"
  if ! ask_yes_no "Reconfigure WordPress sites and rewrite it?" "y"; then
    echo "Keeping $ENV_FILE — starting MCP…"
    $COMPOSE -f docker-compose.prod.yml --env-file "$ENV_FILE" up -d --build mcp
    exit 0
  fi
fi

echo
echo "Add WordPress sites (plugin installed + connection token from wp-admin)."
echo "You will be asked URL and token for each site — no JSON needed."
echo

sites_json='[]'
index=1

while true; do
  echo "--- Site $index ---"
  url="$(ask "WordPress site URL (https://…)")"
  if [[ -z "$url" ]]; then
    echo "URL is required." >&2
    continue
  fi
  case "$url" in
    http://*|https://*) ;;
    *)
      echo "URL must start with http:// or https://" >&2
      continue
      ;;
  esac

  token="$(ask_secret "Connection token")"
  if [[ -z "$token" ]]; then
    echo "Token is required." >&2
    continue
  fi

  default_id="$(
    python3 - "$url" <<'PY'
import sys
from urllib.parse import urlparse
host = urlparse(sys.argv[1]).hostname or "site"
clean = "".join(ch if ch.isalnum() or ch in "-." else "-" for ch in host.lower())
print(clean.strip("-.") or "site")
PY
  )"
  site_id="$(ask "Site id" "$default_id")"
  site_name="$(ask "Site name" "$site_id")"

  sites_json="$(
    SITES_JSON="$sites_json" SITE_ID="$site_id" SITE_NAME="$site_name" SITE_URL="$url" SITE_TOKEN="$token" python3 <<'PY'
import json, os
sites = json.loads(os.environ["SITES_JSON"])
sites.append(
    {
        "id": os.environ["SITE_ID"].strip(),
        "name": os.environ["SITE_NAME"].strip(),
        "url": os.environ["SITE_URL"].strip().rstrip("/"),
        "token": os.environ["SITE_TOKEN"],
    }
)
print(json.dumps(sites, separators=(",", ":")))
PY
  )"

  index=$((index + 1))
  if ask_yes_no "Add another site?" "n"; then
    echo
    continue
  fi
  break
done

public_url="$(ask "MCP public URL (ChatGPT connector base)" "http://localhost:3000")"
public_url="${public_url%/}"
auth_mode="$(ask "MCP auth mode (mixed|oauth|static|none)" "static")"
auth_secret=""
if [[ "$auth_mode" == "static" || "$auth_mode" == "mixed" ]]; then
  auth_secret="$(ask "MCP auth secret (blank = generate)" "")"
  if [[ -z "$auth_secret" ]]; then
    auth_secret="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    echo "Generated MCP_AUTH_SECRET (saved in $ENV_FILE)."
  fi
fi

umask 077
SITES_JSON="$sites_json" \
PUBLIC_URL="$public_url" \
AUTH_MODE="$auth_mode" \
AUTH_SECRET="$auth_secret" \
ENV_PATH="$ENV_FILE" \
python3 <<'PY'
import json, os
from pathlib import Path

sites = json.loads(os.environ["SITES_JSON"])
path = Path(os.environ["ENV_PATH"])
lines = [
    "# Generated by scripts/mcp-up.sh — do not commit",
    f"WORDPRESS_SITES={json.dumps(json.dumps(sites, separators=(',', ':')))}",
    f"MCP_PUBLIC_URL={os.environ['PUBLIC_URL']}",
    f"MCP_AUTH_MODE={os.environ['AUTH_MODE']}",
    f"MCP_AUTH_SECRET={json.dumps(os.environ['AUTH_SECRET'])}",
    "MCP_AUTH_DISABLED=false",
    "MCP_PORT=3000",
    "MCP_HOST=0.0.0.0",
    "MCP_PUBLISH=127.0.0.1:3000:3000",
    "OAUTH_DATA_DIR=/app/data/oauth",
]
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

echo
echo "Wrote $ENV_FILE"
echo "Starting MCP container…"
$COMPOSE -f docker-compose.prod.yml --env-file "$ENV_FILE" up -d --build mcp

echo
echo "MCP endpoint: ${public_url}/mcp"
echo "Health:       curl -fsS ${public_url}/health"
if [[ "$auth_mode" == "static" || "$auth_mode" == "mixed" ]]; then
  echo "Auth mode:    ${auth_mode} (secret in $ENV_FILE)"
fi
echo "Logs:         make prod-logs"
echo "Stop:         make mcp-down"
